site_name: "Docs: Pixie Boot"

repo_name: hackedpixels/pixie_boot
repo_url: https://github.com/hackedpixels/pixie_boot

# Copyright notice
copyright: Copyright &copy; 2023 Jan K&ouml;ppen

theme:
  name: material
  features:
  - content.tabs.link
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

plugins:
- mike

markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true

extra:
  version:
    default: stable
    provider: mike

